name: Agent release

on:
  push:
    paths-ignore:
      - "script/**"
      - ".gitignore"
      - "*.md"
      - "cmd/dashboard/**"
      - ".github/workflows/dashboard.yml"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
